### ISSUE TITLE
vulnerability not showing on the extension 

### ISSUE THREAD

**Issue by louisdubuc95** [blackducksoftware/black-duck-radar#16]
I currently have an issue where BlackDuck Radar is not showing vulnerabilities from a vulnerable component. But it is showing vulnerable on Snyk. 

Link: 
https://www.npmjs.com/package/loopback/v/2.42.0
https://snyk.io/test/npm/loopback/2.42.0

![NPM](https://user-images.githubusercontent.com/11632456/74459975-2c91d780-4e5a-11ea-946b-3bfc6bd81f22.PNG)

![imgpsh_mobile_save](https://user-images.githubusercontent.com/11632456/74460314-b0e45a80-4e5a-11ea-9f03-2b48b09781c0.jpg)

**Comment by jamesrichard91** [comment]
We will look into why the vulnerabilities are missing.

**Comment by jamesrichard91** [comment]
The versions that are effected by those vulnerabilities are being updated but our team has discovered that Snyk is falsely reporting vulnerabilities for Loopback 2.42.0.

Notes on BDSA-2019-4256 (snyk report: https://snyk.io/vuln/SNYK-JS-LOOPBACK-174846)
The vulnerability is being reported by snyk as SQLi. The initial report to the vendor stated that this is a "Query injection" (https://github.com/strongloop/loopback/issues/4195).  The team found that this is a form of object injection.  There  is no SQL injection into a statement.
 
Notes on  BDSA-2019-4260 (https://snyk.io/vuln/npm:loopback:20171027)
This vulnerability is reported by snyk to affect version <3.16.2. The team found that the two vulnerable endpoint were introduced in version 3.6.0, and 3.7.0 (as stated in the BDSA). Therefore earlier versions will not be vulnerable.  Meaning snyk flagged a false positive, 2.42.0 is not vulnerable, that is why a scan using Radar does not show this vulnerability. The vendor has the wrong fixed version in their advisory (https://loopback.io/doc/en/sec/Security-advisory-10-24-2017.html).  They state this is fixed in 3.16.0. Only one of the two vulnerable endpoints were fixed in this release.
