### ISSUE TITLE
No options to save credentials

### ISSUE THREAD

**Issue by EmmanuelCanaan** [blackducksoftware/black-duck-radar#2]
This is very interesting, but there appears to be no option to save credentials, requiring constant sign in. Is it possible to add a way to store credentials in an encrypted form?

**Comment by bthallion** [comment]
We've been cautious about persisting Hub credentials in Radar because it isn't absolutely secure to do so, if someone gained access to your computer they could decrypt your credentials
https://stackoverflow.com/questions/3265348/storage-of-passwords-in-google-chrome-extension

We're planning to add OAuth support to the Hub in a future release, and when we do so we can persist the access token to cut down on the number of authentications.

**Comment by psantos1113** [comment]
Looking into using tokens for authentication.

**Comment by psantos1113** [comment]
We use api tokens now that you retrieve from the BlackDuck product.  This is now the mechanism to authenticate with the extension.

**Comment by rock-a-rolla** [comment]
I am not able to save my API token while attempting to configure the extension, although I appear to be doing everything right (valid server, valid token). When I click "save," nothing happens, and Radar updates to say "Invalid Configuration." Is this a common issue?
![error](https://user-images.githubusercontent.com/66794143/84415764-3d244580-abe1-11ea-8e2b-b4f28df2bec0.png)
